config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations'}
  resources :ingredients
  resources :categories
  resources :users
  resources :recipes
  root 'recipes#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :joins
  has_many :recipes, through: :joins

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :recipe

end

app/models/join.rb
class Join < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :category
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :joins
  has_many :categories, through: :joins
  belongs_to :user
  has_many :ingredients
  accepts_nested_attributes_for :categories
  accepts_nested_attributes_for :ingredients,
    allow_destroy: true,
    :reject_if => proc {|attr| attr[:title].blank?}

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :recipes
  has_many :ingredients, through: :recipes
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

def new
end

def create
  @ingredient = Ingredient.create(params[:title]) if(params[:title] != "" || params[:title].nil?)
end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!


  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
    @user = User.find(@recipe.user_id)
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @recipe}
    end
  end

  def new
    @recipe = Recipe.new
    @ingredient = @recipe.ingredients.build
    @category = @recipe.categories.build
    @recipe.user_id = current_user.id
  end

  def create
    @recipe = Recipe.create(recipe_params)
    @recipe.user_id = current_user.id
    ingredient = Ingredient.create(params[:ingredients])
    @recipe.ingredients << ingredient unless ingredient.title.nil? || ingredient.title = ""
    redirect_to @recipe
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    authorize @recipe
    @recipe.destroy
    redirect_to root_path
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title, :description, :user_id, ingredient_ids:[], ingredients_attributes:[:title])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @user}
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RecipeRailsSite</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Rails Recipes</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Hello <%= current_user.name.capitalize%> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to("My Recipes", user_path(current_user)) %></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to("Sign out", destroy_user_session_path, :method => :delete) if user_signed_in? %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
  <% end %>


<%= yield %>

</body>
</html>

app/views/recipes/index.html.erb
<h3>Recipes</h3>

<% if @recipes.empty? %>
<h2>Oh No! No Recipes</h2>
<br>
<%end%>

<ul>
  <% @recipes.each do |recipe| %>
    <li><%= link_to recipe.title, recipe_path(recipe) %></li>
  <% end %>
</ul>

<%= link_to "New Recipe", new_recipe_path%>

app/views/recipes/new.html.erb
<%= link_to "Go back", root_path %>

<h3>New Recipe</h3>

<%= form_for @recipe do |f| %>
  Title: <%= f.text_field :title , autofocus: true%> <br> <br>
  Description: <br> <%= f.text_area :description %> <br>
 <br>

 <%= f.hidden_field :user_id%>



  Categories: <br>

   <%= f.select :category_ids, Category.all.collect{|c| [c.title]}.uniq, :prompt => 'Select One' %>



  <br> <br>



  Ingredients: <br>
   <%= f.fields_for :ingredients, @recipe.ingredients.build do |i| %>

      <%= i.text_field :title %>

  <% end %> <br>
  <%= f.fields_for :ingredients, @recipe.ingredients.build do |i| %>

      <%= i.text_field :title %>

  <% end %> <br>
  <%= f.fields_for :ingredients, @recipe.ingredients.build do |i| %>

      <%= i.text_field :title %>

  <% end %> <br>

  <%= f.submit %>
<% end %>

app/views/recipes/show.html.erb
<h2><div class="recipeTitle"><%= @recipe.title %></div></h2>
<h3><div class="recipeDescription"><%= @recipe.description%></div></h3>
</div>
<div class="linkUser">
  <%= link_to @user.name , user_path(@user) %>
</div>
<br>
<a href="#" class="js-next" data-id="<%=@recipe.id%>">Next...</a>
<div class="ingredients">
  <% @recipe.ingredients.each do |ingredient| %>
    <li><%= ingredient.title %></li>
  <% end %>
</div>
<div>
<% if policy(@recipe).destroy? %>
  <%= link_to "Delete", recipe_path(@recipe), method: :delete %>
<% end %>
</div>

<script type="text/javascript" charset="utf-8">
$(function () {
  $(".js-next").on("click", function() {
    var nextId = parseInt($(".js-next").attr("data-id")) + 1;
    $.get("/recipes/" + nextId + ".json", function(data) {
      $(".recipeTitle").text(data["recipe"]["title"]);
      $(".recipeDescription").text(data["recipe"]["description"]);
      $(".postTitle").text(data["recipe"]["user"]["name"]);
      var userName = data["recipe"]["user"]["name"];
      var userId = data["recipe"]["user"]["id"];
      $(".linkUser").html("<a href='/users/" + userId + "' >" + userName + "</a>");
      var ingredients = data["recipe"]["ingredients"];
      for(var i = 0; i < ingredients.length; i++){
        $(".ingredients").html("<li>" + ingredients[i]["title"] +"</li>")
      }
      // re-set the id to current on the link

      $(".js-next").attr("data-id", data["recipe"]["id"]);

    });
  });
});
</script>

app/views/users/show.html.erb
<h2><%= @user.name %>'s Recipes </h2>

<ul>
  <% @user.recipes.each do |recipe| %>
    <li><%= link_to(recipe.title, recipe_path(recipe))%></li>
  <% end %>
</ul>